import Navbar from "src/app/components/navbarTrainer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TraineeLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar /> {/* Navbar is rendered by default */}
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
