import localFont from "next/font/local";
import Image from "next/image";
import Link from "next/link";
import Navbar from "src/app/components/navbarMylearning";

// Define custom fonts (uncomment if needed)
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// Define metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the layout component
export default function TraineeLayout({ children, noNavbar }) {
  return (
    <html lang="en">
      <body>
        <div>
          {/* Conditionally render the Navbar */}
          {!noNavbar && <Navbar />}

          {/* Render the children (page content) */}
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}