import Navbar from "src/app/components/navbarMylearning";

// Define metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the layout component
export default function TraineeLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>
          {/* Always render the Navbar */}
          <Navbar />

          {/* Render the children (page content) */}
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
